1024pix/pix-ui

.storybook/preview.js
.storybook/storybook-custom-theme.js
package-lock.json
package.json

Cette PR résoud un bug introduit avec https://github.com/1024pix/pix-ui/pull/7 .
Elle permet de plus de centrer le contenu de toutes les stories.
Afin de centrer les stories nous avons installé : [l'addon centered ](https://github.com/storybookjs/storybook/tree/master/addons/centered). [Autre lien utile au sujet de cet addon avec ember.](https://github.com/storybookjs/ember-cli-storybook/issues/18) 
Pour enlever l'action de l'addon sur une story en particulier, il suffit de rajouter dans les paramètres d'une story :  ```centered: { disable: true } ```.
Ce qui donne, par exemple, dans `pix-tooltip.stories.js` : 
```javascript
// ... 
tooltip.story = {
parameters: {
centered: { disable: true },
notes: {
markdown,
},
},
};
```
Créer un composant et sa story, constater que son contenu se …

[TECH] Correction d'un bug venant du theme et centrer les stories

---

package-lock.json
package.json

Comme suggeré dans la [doc de storybook pour le déploiement](https://storybook.js.org/docs/basics/exporting-storybook/) j'ai installé [storybook-deployer](https://github.com/storybookjs/storybook-deployer).
Ce dernier permet de déployer automatiquement une version statique de storybook sur la branche `gh-pages`. 
Pour ce faire il suffit de taper : `npm run deploy-storybook` à partir de la branche qu'on souhaite voir se déployer sur `https://1024pix.github.io/pix-ui/`.
🔴  : ATTENTION `npm run deploy-storybook` add et push tout seul à votre place sur la branche `gh-pages`.
🟠  : ATTENTION il n'existe qu'une seule branche `gh-pages` , donc qu'un seul déploiement de storybook en ligne. Ce genre de déploiement devra donc s'effectuer pour les Mises En Production de pix-ui et non pas sur chacune …

[TECH] Ajout d'un script de déploiement de storybook sur GitHub Pages

---

CHANGELOG.md
scripts/get-pull-requests-to-release-in-prod.js
scripts/publish.sh

Le changelog est split en un tableau avec "3 types d'éléments" : "titre", "saut de ligne", "contenu (PR ajoutées)".
L'index où on ajoutait le nouveau contenu du changelog vallait par défaut 2. 
Pour les autres app le changelog avait un titre + saut de ligne, d'où cet ajout **après les 2 premiers éléments** du changelog.
Dans le changelog de pix-ui nous n'avions pas rajouté de titre. 
2 solutions : 
- ajouter un titre
- ou mettre par défaut l'ajout des nouveaux éléments à l'index 0
J'ai choisis la première solution car elle + iso aux autres app.

[TECH] Correction de l'ordre des titres du Changelog

---

addon/components/pix-tag.hbs
addon/stories/pix-tag.stories.js
addon/styles/_pix-tag.scss
addon/styles/addon.scss
app/components/pix-tag.js
tests/integration/components/pix-tag-test.js

Un Tag est un type de componsant Chips qui permet de mettre en avant une information ou bien de la catégoriser.
> Il est possible de surcharger le style d'un \`<PixTag>\` via l'attribut \`class\` ainsi que de passer n'importe quel attribut sur sa \`div\` wrapper (par exemple, un \`aria-label\`)
Exemple d'utilisation dans Pix-Orga:
Le Tag est un sous composant de la catégorie Chips (voir design-system)
https://app.abstract.com/projects/ff1da878-3f3a-4299-9c47-fad5841962f7/branches/master/commits/b6449eab7c983990a561c4eb2dbfd07f8ccec23d/files/DD03E7C8-8D2E-487B-A863-74B75273DC80/layers/BF78658E-35AF-4765-A78A-588A3311B92F?mode=build&selected=root-BF78658E-35AF-4765-A78A-588A3311B92F
Pour le moment, ce composant a été déclinée uniquement en 3 couleurs (dont 2 utilisées actuellement dans …

[FEATURE] Ajout du composant PixTag

---

package-lock.json
package.json

Certaines dépendances étaient en "dependencies" et non pas en "devDependencies".
Cette réflexion a été initiée par [cette discussion](https://github.com/1024pix/pix/pull/1483/commits/d6d88fd701216be75abceac3bd2a8c89db96f2f4#r435275628).
"dependencies": c'est ce qui est utile à la prod (donc utile à l'installation de notre addon ember sur une autre app).
"devDependencies": utile au développement mais pas au produit final.
=> le build du produit final est considéré comme une étape "dev" de toute manière donc on met tout dans "devDependencies"

[TECH] Mettre des dépendances en "devDependancies"

---

package-lock.json
package.json

Suite à la PR https://github.com/1024pix/pix-ui/pull/20, le script de release de Pix-UI crashait au moment de déployer storybook (le reste a fonctionné correctement et le déploiement de storybook est la dernière étape).
Après de multiple tests je me suis rendue compte que **tant que** la dépendance `"@storybook/addon-notes"` n'était pas dans les "dependencies" le script de déploiement de storybook sur les github pages ne fonctionnait pas.
De plus il est à noter que si "ember-cli-sass" n'est pas non plus dans les "dependencies" il n'y aura aucun style dans nos canvas sur le storybook en ligne. (Ce qui est un peu embêtant quand on souhaite prévisualiser nos composant avec leur style 🙄 ).
- se mettre sur cette branche
- `npm ci`
- `npm run deploy-storybook`
=> constater que le script finis …

[TECH] Correction du déploiment automatique de storybook en ligne

---

.storybook/preview.js
addon/components/pix-background-header.hbs
addon/components/pix-background-header.js
addon/components/pix-block.hbs
addon/components/pix-block.js
addon/stories/pix-background-header.stories.js
addon/stories/pix-block.stories.js
addon/stories/pix-message.stories.js
addon/stories/pix-tag.stories.js
addon/stories/pix-tooltip.stories.js
addon/styles/_breakpoints.scss
addon/styles/_colors.scss
addon/styles/_pix-background-header.scss
addon/styles/_pix-block.scss
addon/styles/addon.scss
app/components/pix-background-header.js
app/components/pix-block.js
tests/integration/components/pix-background-header-test.js
tests/integration/components/pix-block-test.js

Dans le contexte du [design du nouveau certificat](https://github.com/1024pix/pix/pull/1577) j'en profite pour rajouter ces deux composants à Pix UI : 
- PixBackgroundBlue : la bande bleu en haut de page sur mon-pix
- PixBlocShadow : un bloc blanc avec les bords arrondis
En somme ces deux composants imbriqué, permettent de faire ceci : 
Les deux composants sont responsives (ensemble et séparément). Leur modèles (version certificat) sont présents sur ce lien : https://app.abstract.com/projects/3e4937ef-48a8-408b-9edd-1f69dab81b39/branches/288b95d2-6697-44a9-a4ba-2339a4480aad/collections/4ea4253d-5685-4ffc-afaa-632e144ec8f4
- `npm i`
- `npm run storybook` 😉

[FEATURE] Ajout d'un PixBackgroundBlue & PixBlocShadow

---

.ember-cli

L'app tournait sur le port 4200 (qui est le même que mon-pix). Ce n'est pas pratique lorsqu'on souhaite faire tourner les deux app en parallèle.
Je propose donc de changer ce port pour le 4204 (à la suite de certif qui est le 4203).
https://guides.emberjs.com/release/configuring-ember/configuring-ember-cli/
- `npm start` > vérifier que le port est bien 4204
- aller sur `localhost:4204/tests` par exemple

[TECH] Changer le port de l'app Ember Pix UI

---

addon/styles/_pix-message.scss
addon/styles/_pix-tag.scss
addon/styles/_pix-tooltip.scss
addon/styles/_reset-css.scss

Certains éléments ne s'affichent pas pareil d'un navigateur à l'autre. 
L'avantage d'un reset CSS est de minimiser ces écarts, et donc moins de soucis de css venant des navigateurs.
[Un peu plus d'explication sur les reset CSS ici.](https://www.alsacreations.com/astuce/lire/36-reset-css.html)
Le reset CSS qu'on a choisis de mettre en place est le suivant : http://maxdesign.com.au/articles/css-reset/. 
Si vous avez d'autres propositions avis n'hésitez pas :) 
Ajouter un fichier reset CSS préfixé par "_" et l'inclure dans chacun de nos composants.
**ATTENTION** : cela implique d'ajouter le reset css dans la classe parent de chaque composant  : 
```scss 
.pix-nom-du-composant {
@import 'reset-css';
// le style que je veux ensuite
}
```
Avec @D0C702WH0 on était tombé sur des différences …

[TECH] Ajout d'un reset CSS

---

.storybook/manager.js
.storybook/preview.js
addon/stories/pix-background-header.stories.js
addon/stories/pix-block.stories.js
addon/stories/pix-link-back.stories.js
addon/stories/pix-message.stories.js
addon/stories/pix-tag.stories.js
addon/stories/pix-tooltip.stories.js
addon/styles/_pix-background-header.scss
addon/styles/_pix-return-to.scss

+ Petites corrections de quelques warnings que lançait storybook : 
+ création d'une section "Layout" dans le menu de storybook pour les composants BackgroundHeader & Block
+ rajout du reset.css là où il manquait
- npm run storybook
- ouvrir la console (fn + F12) : checker qu'il n'y a plus de warnings

[TECH] Correction des warnings de storybook

---

addon/components/pix-banner.hbs
addon/components/pix-banner.js
addon/stories/pix-banner.stories.js
addon/styles/_pix-banner.scss

PixBanner crée systématiquement des liens externes à partir de la propriété actionUrl. Le composant ne supporte pas de route ember en entrée (ex: authenticated.sco-students). 
On cherche dans actionUrl un slash pour vérifier si c'est un lien externe ou interne.
Il n'y a pas de routeur dans storybook pour tester il faut prendre le hash du commit et installer la version de cette branche dans PixOrga.
```sh
npm install git://github.com/1024pix/pix-ui.git#3cf42e16ccabc7b12b5998c3c14d960d4d5248ae
```
Se connecter avec le compte sco et mettre une route en paramètre de PixBanner et constater que en cliquant sur le bouton on est bien redirigé vers la route en question.

[FEATURE] Add support for ember app internal links in PixBanner (PIX-1085).

---

.circleci/config.yml

Le build circle-ci échoue sur la branche gh-pages de pix-ui car sa config n'est pas présente.
Eviter de jouer circle-ci sur la branche gh-pages.

[TECH] Eviter de jouer circle-ci sur la branche gh-pages

---

addon/components/pix-action-button.hbs
addon/components/pix-action-button.js
addon/stories/pix-action-button.stories.js
addon/styles/_pix-action-button.scss
addon/styles/addon.scss
app/components/pix-action-button.js
tests/integration/components/pix-action-button-test.js

Mise en place du composant `PixActionButton` qui permet de créer un bouton à partir d'une icon.
Exemple de PixActionButton:
Cette PR sera utilisée et mergée lors du bootcamp Pix-UI du 24/09.
Maquette : 
https://zeroheight.com/8dd127da7/p/20d723-floating-action-button-fab
Implémentation : 
- `npm run storybook`

[FEATURE] Créer le composant PixActionButton

---

addon/components/pix-stars.hbs
addon/components/pix-stars.js
addon/stories/pix-stars.stories.js
addon/styles/_pix-stars.scss
addon/styles/addon.scss
app/components/pix-stars.js
package-lock.json
package.json
tests/integration/components/pix-stars-test.js

Dans le cadre des paliers, nous avons besoin d'un composant pour afficher des étoiles.
Nous avons un composant `<PixStars>` réutilisable dans de multiples usages:
```
<PixStars 
@total={{5}}
@count={{2}}
@alt="message alt"
@color="blue"
/>
```
Nous nous sommes basé sur les étoiles (paliers) dans pix-app et sur les [nouvelles maquettes pour pix-orga](https://app.abstract.com/projects/fa298ac7-3ab1-4888-8156-7d142235b3a5/branches/5c9467c8-87f6-4361-aeb5-ee8919476d40/commits/a1b6745e8f75d39a3733d89ca1aae6d59973675d/files/990ED997-76F5-46E7-9A70-DF7994551675/layers/5C18BBF6-9EB2-4024-934D-21AC39E56DAD?collectionId=c101cc47-43bf-43f7-b598-a6b7d4c004bf&collectionLayerId=709abd45-ee59-4eb6-a8b3-9247f0dba7c4&mode=design)

[FEATURE] Ajout du composant PixStars (pix-1448)

---

addon/styles/_pix-stars.scss

Les étoiles bleues "vides" de PixStars ne doivent pas avoir de bordure.
Résultat:

[STYLE] Les étoiles bleues "vides" de PixStars ne doivent pas avoir de bordure

---

addon/components/pix-button.hbs
addon/components/pix-button.js
addon/stories/pix-button.stories.js
tests/integration/components/pix-button-test.js

- Pouvoir passer le type du bouton, pour pouvoir passer le type submit
- Passer les paramètres reçus à la fonction, pour pouvoir passer notamment les event lors des clics
- Sans type indiqué, le type de base est "button"

[BUGFIX] Amélioration du Pix-Button pour les formulaire

---

addon/styles/_pix-return-to.scss

La PixReturnTo permet de revenir sur une page précédente.
Selon les pages et le contexte la PixReturnTo paraît petite et peut donc être difficile à lire.
Grossir le texte et enlever un peu de bold.

[DesignFix] Corriger le design de la PixReturnTo

---

addon/components/pix-select.hbs
addon/stories/pix-select.stories.js
addon/styles/_pix-select.scss
addon/styles/addon.scss
app/components/pix-select.js
package-lock.json
package.json
tests/integration/components/pix-select-test.js

Dans pix-orga nous utilisons à plusieurs endroits un composant `select` basique avec le style défini par le design system.
Ce composant devrait être partagé pour tout pix.
`ember-sinon` a été ajouté afin de pouvoir réaliser les tests

[FEATURE] Ajout du composant pix-select

---

.circleci/config.yml

CircleCi continue de lancer des vérifications sur la branche gh-pages.
Une PR sur le sujet avait déjà été ouverte : https://github.com/1024pix/pix-ui/pull/32
Il semblerait que quelqu'un ait déjà eu exactement le même soucis : https://discuss.circleci.com/t/excluding-a-branch-from-ci/17811
Le problème viendrait donc du `filters` qui doit être placé dans la partie `workflow` et non `jobs`. 
Documentation circle ci sur les `fitlers` : https://circleci.com/docs/2.0/configuration-reference/#filters-1

[TECH] Ne pas lancer circle-ci sur la branche gh-pages

---

package.json

**Circle Ci se lance à chaque fois sur la branche `gh-pages`.**
La branche `gh-pages` contient uniquement des fichiers buildé afin de déployer, en tant que site statique, notre application storybook :  `1024pix.github.io/pix-ui/`. Par ailleurs, **le contenu de la branche `gh-pages` est généré automatiquement** grâce à la commande `npm run deploy-storybook` (voir [storybook-deployer](https://github.com/storybookjs/storybook-deployer)).
Nous avons fait plusieurs essais pour ne pas déployer la ci sur cette branche là : 
- https://github.com/1024pix/pix-ui/pull/32
- https://github.com/1024pix/pix-ui/pull/43
Mais rien n'était concluant. Après un message sur les forums de circleci **la solution qui a été proposée était de dupliquer le fichier `config.yml` sur la branche `gh-pages`**. Voir …

[TECH] Skip la CI sur les gh-pages

---

README.md
addon/components/pix-filter-banner.hbs
addon/components/pix-filter-banner.js
addon/stories/pix-filter-banner.stories.js
addon/styles/_pix-filter-banner.scss
addon/styles/addon.scss
app/components/pix-filter-banner.js
tests/integration/components/pix-filter-banner-test.js

Ajout d'un composant permettant de wrapper les composants de "select", "input", "multi-select" de manière cohérente et jolie. Les composants que l'on peut mettre à l'intérieur sont configurables.
Dans Pix Orga, cela donne :
Comme le titre est configurable, cela pourrait être une bannière pour wrapper n'importe quoi d'autre. Mais du coup je ne sais pas comment la nommer. Des idées ?
Sur Storybook

[FEATURE] Création du composant de bannière de filtres (PIX-1675).

---

addon/components/pix-button.js
addon/stories/pix-button.stories.js
tests/integration/components/pix-button-test.js

`action` est un mot clé pour ember. Du coup, l'utilisation de PixButton peut déclancher des erreurs, notamment : 
`no-action: Do not use 'action' as {{action ...}}. Instead, use the 'on' modifier and 'fn' helper.`.
Pour plus de détail voir : https://1024pix.slack.com/archives/CFVNK8QQJ/p1607522423009700 
Changer le nom du paramètre `action` pour `triggerAction`.

[TECH] Ne pas utiliser de mot clé ember comme nom de paramètre

---

.circleci/config.yml

Le linter n'est pas exécuté par la CI sur chaque PR, ce qui fait que des PR sont mergées avec un linter invalide.
> _Des infos supplémentaires, trucs et astuces ?_
Vérifier que le linter est bien passé dans le build circle-ci de cette PR

[TECH] Ajouter le linter aux build circle-ci

---

addon/components/pix-button.js
addon/stories/pix-button.stories.js

Lorsqu'on utilise PixButton côté front et qu'on ne met pas le paramètre @triggerAction on a un message d'erreur pas très explicite : `TypeError: this.args.triggerAction is not a function` 
Ce qui peut porter à confusion et faire croire que l'erreur vient côté front, alors qu'elle vient du PixButton.
Envoyer un message plus explicite lorsqu'on ne passe pas @triggerAction. 

[TECH] Envoyer un message d'erreur plus explicite pour le PixButton

---

addon/stories/pix-tag.stories.js
addon/styles/_pix-tag.scss

Pour  https://github.com/1024pix/pix/pull/2268 nous avons besoin de la variante jaune du composant `PixTag`. 
Nous avons également rajouter la variante grise qui sera nécessaire dans la page *Mes Parcours*.
En bonus, la variante verte a été modifié pour avoir le contraste minimum pour des raisons d'accessibilité.

[FEATURE] Ajout des variantes jaunes et grises pour le composant PixTag

---

addon/components/pix-tag.hbs
addon/stories/pix-tag.stories.js
addon/styles/_pix-tag.scss
tests/integration/components/pix-tag-test.js

Nous avons besoin d'une variante avec le contenu du tag en majuscule. Nous avons rajouté un argument uppercase pour cela.
_Néant_

[Feature] Ajout de l'argument uppercase sur le composant PixTag
